version: 0.2
phases:
  pre_build:
    commands:
      - echo "Starting build process..."
  build:
    commands:
      - echo "Copying DAG files to S3..."
      - aws s3 cp --recursive --debug "./dags" "s3://airflow-custom/dags/"
      - echo "Copying DAG files to S3..."
      - aws s3 cp --debug "./aws-requirements.txt" "s3://airflow-custom/requirements/requirements.txt"
      - echo "Copying dim data files to S3..."
      - aws s3 cp --recursive --debug "./data" "s3://food-delivery-stream-bucket/dims/"
      - echo "Copying pyspark scripts to S3..."
      - aws s3 cp --debug "./scripts/pyspark_streaming.py" "s3://food-delivery-stream-bucket/pyspark_scripts/pyspark_streaming.py"
      - echo "Copying redshift jar file to S3..."
      - aws s3 cp --recursive --debug "./jars" "s3://food-delivery-stream-bucket/jars/redshift-connector-jar/"
  post_build:
    commands:
      - echo "Build and deployment process complete!!!"