version: 0.2
phases:
  pre_build:
    commands:
      - echo "Starting build process..."
  build:
    commands:
      - echo "Copying DAG files to S3..."
      - aws s3 cp --recursive --debug "./dags" "s3://airflow-custom-dags/dags/"
      - echo "Copying DAG files to S3..."
      - aws s3 cp --debug "./requirements.txt" "s3://airflow-custom-dags/requirements/"
      - echo "Copying dim data files to S3..."
      - aws s3 cp --recursive --debug "./data" "s3://food-delivery-stream/dims/"
      - echo "Copying pyspark scripts to S3..."
      - aws s3 cp --debug "./scripts/pyspark_streaming.py" "s3://food-delivery-stream/pyspark_scripts/pyspark_streaming.py"
      - echo "Copying redshift jar file to S3..."
      - aws s3 cp --recursive --debug "./jars" "s3://food-delivery-stream/jars/redshift-connector-jar/"
  post_build:
    commands:
      - echo "Build and deployment process complete!!!"